name: pasell
description: A Complete app.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.0.0
  google_fonts: ^3.0.1
  flutter_secure_storage: ^5.0.2
  http: ^0.13.2
  form_field_validator: ^1.1.0
  flutter_svg: ^1.1.1+1
  animate_do: ^2.0.0
  image_picker: ^0.8.5+3
  flutter_rating_bar: ^4.0.0
  shimmer: ^2.0.0
  flutter_screenutil: ^5.3.1
  dropdown_search: ^5.0.2
  flutter_stripe: ^4.0.0
  shake: ^2.0.0
  proximity_sensor: ^1.0.2
  awesome_notifications: ^0.6.21
  watch_connectivity: ^0.1.0
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  wearable_rotary: ^1.0.2
  wear: ^1.1.0
  flutter_toast_message: ^0.0.1
  google_maps_flutter: ^2.0.10
  flutter_local_notifications: ^12.0.3+1
  flutter_riverpod: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0
  build_runner: ^2.2.0
  flutter_lints: ^2.0.1

flutter_icons: 
  android: true
  ios: true
  image_path: "Assets/icon.png"



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - images/
    - Assets/
    - Assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700