// Mocks generated by Mockito 5.1.0 from annotations
// in aimsdigital/test/Controller/AuthController_test.dart.
// Do not manually edit this file.

// @dart=2.9

import 'package:pasell/Controller/AuthController.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: camel_case_types

/// A class which mocks [AuthController].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthController extends _i1.Mock implements _i2.AuthController {
  MockAuthController() {
    _i1.throwOnMissingStub(this);
  }
}
